sync:
	@echo "Updating dot files ..."
	@cp ~/.bash_profile .
	@cp ~/.bashrc .
	@cp ~/.gitconfig .
	@cp ~/.vimrc .
	@cp ~/.xprofile .
	@cp ~/.xinitrc .
	@echo "Done."
	@echo "Updating suckless configurations ..."
	@cp ~/builds/st/config.h builds/st/
	@cp ~/builds/dwm/config.h builds/dwm/
	@cp ~/.local/bin/dwm_status .local/bin/
	@echo "Done."
