sync:
	@echo "Updating dot files ..."
	@cp ~/.bash_profile .
	@cp ~/.bashrc .
	@cp ~/.gitconfig .
	@cp ~/.gitrepos .
	@cp ~/.vimrc .
	@cp ~/.xprofile .
	@cp ~/.xinitrc .
	@cp ~/.latexmkrc .
	@cp ~/.config/dunst/dunstrc .config/dunst/
	@cp -r ~/.scim .
	@echo "Done."
	@echo "Updating suckless configurations ..."
	@cp ~/builds/st/config.h builds/st/
	@cp ~/builds/dwm/config.h builds/dwm/
	@cp -r ~/.local/bin .local/
	@echo "Done."
